version: '3'

services:
  postgres:
    restart: always
    build:
      context: ./postgres
      dockerfile: Dockerfile.dev
    ports:
      - '5432:5432'
  api:
    restart: always
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    ports:
      - '2100:80'
    volumes:
      - './api:/app'
  # frontend:
  #   restart: always
  #   image: nginx:1.21-alpine
  #   ports:
  #     - '2200:80'
  #   volumes:
  #     - './frontend:/usr/share/nginx/html'
  angular:
    restart: always
    build:
      context: ./angular
      dockerfile: Dockerfile.dev
    ports:
      - '2300:4200'
    volumes:
      - './angular:/app'
