version: '3'

services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    ports:
      - '2100:80'
    volumes:
      - './api:/api'
  frontend:
    image: nginx:1.21-alpine
    ports:
      - '2200:80'
    volumes:
      - './frontend:/usr/share/nginx/html'
