version: '3'

services:
  app:
    build: ./src/app
    ports:
      - '80:80'
    volumes:
      - './src/app:/app'
  postgres:
    build: ./src/postgres
    ports:
      - '5432:5432'
  angular:
    build: ./src/angular
    ports:
      - '2300:4200'
    volumes:
      - './src/angular:/app'
