version: '3'

services:

  postgres:
    build: ./src/postgres
    ports:
      - '5432:5432'

  api:
    build: ./src/api
    ports:
      - '80:80'
    volumes:
      - './src/api:/app'

  # frontend:
  #   image: nginx:1.21-alpine
  #   ports:
  #     - '2200:80'
  #   volumes:
  #     - './src/frontend:/usr/share/nginx/html'

  angular:
    build: ./src/angular
    ports:
      - '2300:4200'
    volumes:
      - './src/angular:/app'
